### ISSUE TITLE
RFC - Move stack to separate AWS account

### ISSUE THREAD

**Issue by evilmarty** [everydayhero/buildkite-aws-stack#54]
# Background
The stack currently resides in our staging AWS account in its own VPC. The structure is 2 private and public subnets being a total of 4. Each public subnet has a NAT associated with a public IP address and is routed to accept external traffic from the private subnets. 2 private S3 buckets are configured, one for secrets and the other for build artifacts. The artifacts have a shelf life of 7 days, after which are automatically deleted to not incur long-term charges. This is all managed by Terraform while the Auto Scale Group and EC2 instances are managed by Buildkite's CloudFormation template.

All pipelines interact with the staging VPC via external channels with no VPC bridging. Also, there are pipelines which require launching EC2 instances which are currently done inside that VPC.

# Problem
While this may seem trivial there are major facets that may not seem obvious at first but will go into each one to give a better understanding.

## Resource limitations
Each AWS account is limited to a maximum 10 Elastic IP addresses. With 2 of them being used for the NATs that reduces the number for the staging account down to 8. 3 are used for the staging account, 1 for the bastion, 3 for Convox, etc. What this means is it becomes difficult and require juggling EIPs for testing and development purposes.

## Security
Sharing our build environment with staging runs the risk that either environments can interact with each other not from a networking level but a services level. What this means that because some of the IAM policies lack granularity or are just limited can be leveraged to interact with each other's resources. ie. S3 buckets, users, roles, security groups, etc. Thus requires more diligence when assigning access to applications and services running in either environment.

## Separation of concerns and staging/production disparity
There's a vast number of inconsistencies between staging and production because we are limited to only 2 environments and fail to realise when something is neither. We cannot say production is a subnet of staging and vice versa because there are differences on both sides.

# Solutions

## Move build stack into a separate environment/AWS account

*Pros*
* Isolation
* Better staging/production parity
* All builds are treated equal
* Better cost breakdown per environment
*Cons*
* Another AWS account to manage
* Duplicating user accounts (based on current setup)
* Most effort to implement

## Mimic staging into production

*Pros*
* Better staging/production parity
* Separate staging and production concerns into their respective environments
* Can restrict/remove environment cross-over
* Utilise existing user accounts
*Cons*
* Doesn't address risk builds and apps can interact with each other's AWS resources
* Doesn't address concerns that are specific to staging or production
* Still contributes to resource limits

# Recommendation

Moving the build stack into its own environment makes it much easier to police usage and restrictions and makes it easier to identify malicious usage for all environments. It will also bring staging and production more align and close enough to have identical configurations.

One of the biggest gains from this change would be the building of custom AMIs which require provisioning EC2 instances and EBS volumes. It would be easier to have a designated VPC, security group, and key pair as a sandbox to be used while creating AMIs. It would also be easy to track because only specific roles would be allowed to perform such actions. Whereas in any other scenario that would have to include numerous exceptions.

**Comment by mbuhot** [comment]
EIPS: Surely amazon will raise that resource limit if we ask. I've heard of crazy legacy apps where there is an EIP per customer.

Security: 👍 for the strong separation of AWS resources between buildkite stack, staging and production. 

Another AWS account to manage: AWS has the organisations feature to manage many accounts (https://aws.amazon.com/organizations/)

Duplicating user accounts: Can we do this as-needed? I suspect most developers will never log in to the buildkite account dashboard or require an API key in that account. Is [ADFS](https://aws.amazon.com/blogs/security/how-to-set-up-sso-to-the-aws-management-console-for-multiple-accounts-by-using-ad-fs-and-saml-2-0/) the long term solution here?

**Comment by evilmarty** [comment]
I've purposefully not mentioned recommendations for managing user accounts etc as that is beyond the scope of this RFC and we are still investigating potential solutions to managing that. This RFC is addressing the issues presented in our current set up.

**Comment by JonathonMA** [comment]
I 👍 purely on the basis that doing CI/CD is not a staging concern. Getting this clear separation is amazing.

Any other advantages are gravy.

**Comment by mbuhot** [comment]
@evilmarty: Which problem is most important to solve? Resource limits, staging-prod parity, or account level security?

I feel we can probably just focus on account level security now, with our PCI audit coming up.
Assuming we just focus on the account separation, can you provide some more detail on what that looks like?

**Comment by evilmarty** [comment]
@mbuhot I thought I made my decision clear in "Recommendation":

> Moving the build stack into its own environment makes it much easier to police usage and restrictions and makes it easier to identify malicious usage for all environments. It will also bring staging and production more align and close enough to have identical configurations.

As for what it would look like. It would be a separate account with only the build stack running inside of it. There may be changes where necessary but again only want to focus on the issues raised in this RFC. I believe changes to the build stack can occur anytime and are not dependant to what is raised in this RFC.

**Comment by mbuhot** [comment]
> It would be a separate account with only the build stack running inside of it. 

- How does the migration process work, do we have two stacks running then cut-over?
- Can you spell out the high level steps involved?
- How much effort is involved? Is this a quick job or something that needs to be traded off against other priorities?

It certainly sounds like the a good direction, but I just don't see enough detail in the current plan to meaningfully evaluate it.

**Comment by evilmarty** [comment]
You're after specifics. Righteo. I don't believe it to be too much effort because the stack is automated via a pipeline etc. All we really need to do it run the Terraform code against the new account and it'll create a new stack in minutes. I'm deciding whether to transition the code from Terraform to CloudFormation because of a dead-locking issue (in which Terraform is waiting for the cluster to update and occupying an agent, the cluster in turn is trying to shut down all agents to update). The only hurdle is moving the S3 buckets but that can be solved by performing the transition out of hours to minimise impact.

**Comment by mbuhot** [comment]
Thanks @evilmarty, sounds good.

[The docs](https://github.com/buildkite/elastic-ci-stack-for-aws#build-secrets) mention that the S3 buckets contain secrets encrypted using KMS. Do we need to upload the same private key to the new account then transfer the encrypted files? Or is there some more complex process of decrypting and re-encrypting with a new key?

👍 From me. Happy to move the details to Jira ticket breakdown.

**Comment by elliot** [comment]
I'm +1.

We've got some weird rules in both environments to handle the build node edge case (specifically around security group access, SSH access, IAM roles, etc), that I would like to see gone.

An extra account to manage shouldn't be an issue. We can reduce the management overhead by using IAM roles.
